### PR TITLE
Implement maintenance view

### LINKED ISSUE #190: Maintenance notifications/ calendar
### What is the problem you are trying to solve with this feature?

Right now, I can't see an easy way to see a consolidated view of upcoming maintenance (or ways of sending notifications about this e.g. via a telegram bot).

### What is the solution you are proposing?

Either a notification centre to push/ surface upcoming maintenance, or a maintenance calendar. Ideally with some degree of integration with telegram/ calendar apps/ etc.

I love your app!

### What alternatives have you considered?

_No response_

### Additional context

_No response_

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

### PR DESCRIPTION
**Pull request by mcarbonne**
## What type of PR is this?

- feature

## What this PR does / why we need it:

Aim of this PR is to implement a maintenance view :
image

- this new section is translated.
- I also factorized code used to list maintenances from an item (which also brings translation).
- I also added translation on main menu.

## Which issue(s) this PR fixes:

Fixes #190 (at least partially)

## Special notes for your reviewer:

I've never used vuejs/nuxt/typescript prior to this MR so except some mistakes :pray:

## Testing

Working as expected within provided devcontainer.

## Summary by CodeRabbit

- **New Features**
  - Introduced a new modal for creating and editing maintenance entries.
  - Added filtering options for viewing maintenance entries (Scheduled, Completed, Both).
  - New API endpoints for managing maintenance entries, including retrieval, updating, and deletion.
  - Enhanced API with detailed maintenance entry management capabilities.
  - Added a new navigation item for "Maintenance" in the application layout.

- **Bug Fixes**
  - Improved error handling for maintenance entry operations.

- **Documentation**
  - Updated API documentation to reflect new endpoints and functionalities.

- **Localization**
  - Expanded localization support for maintenance-related terms in English and French.

- **User Interface**
  - Improved UI for managing maintenance entries with new components and streamlined interactions.

### CODE REVIEW

**Comment by mcarbonne** [comment]
Test image available here: ghcr.io/mcarbonne/homebox:beta

**Comment by tonyaellie** [comment]
This looks really good!

Might be worth adding a title something like this to match other pages.

image


Like how the Locations page has
image

**Comment by mcarbonne** [comment]
> This looks really good!
> 
> Might be worth adding a title something like this to match other pages.
> 
> image
> 
> Like how the Locations page has image

fixed in 1a41c74

**Comment by mcarbonne** [comment]
This PR will be completed with another one (#246) to add new actions to improve workflow.

**Comment by tonyaellie** [comment]
Maybe maintemamces tasks?

**Comment by tankerkiller125** [comment]
I like that more, but Maintenances is already pushing out of the sidebar.

**Comment by mcarbonne** [comment]
I can change it to "maintenance" everywhere. If you agree, I'll push changes tonight.

**Comment by tankerkiller125** [comment]
"Maintenance" it is, confirmed with @katosdev

**Comment by mcarbonne** [comment]
> "Maintenance" it is, confirmed with @katosdev

Fixed in my last commit

**Review by tankerkiller125 — APPROVED** [review]

**Pull request merged**
