### PR TITLE
Only accept common image formats during item creation (fix #165)

### LINKED ISSUE #165: Support HEIC images
### What is the problem you are trying to solve with this feature?

Using HEIC images format

### What is the solution you are proposing?

Support HEIC format

### What alternatives have you considered?

_No response_

### Additional context

_No response_

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

### PR DESCRIPTION
**Pull request by mcarbonne**
## What type of PR is this?
feature

## What this PR does / why we need it:
This PR allow only some common image formats during item creation.

## Which issue(s) this PR fixes:

It might solve #165.
Rather than converting on server-side, let apple devices convert the image for us (https://masteringlaravel.io/daily/2023-10-27-how-to-get-rid-of-heic-files-in-your-app)

## Testing

I don't own any apple device, so I only tested that upload is still working well on other devices.

## Summary by CodeRabbit

- **New Features**
	- Enhanced image upload functionality by restricting accepted file types to PNG, JPEG, and GIF formats. 

This change improves control over the types of images users can upload, ensuring compatibility and quality.

### CODE REVIEW

**Comment by tankerkiller125** [comment]
@katosdev You have Apple devices (or at least phones) that you can test this on right? I have nothing that would create the problem format in the issue.

**Comment by katosdev** [comment]
> @katosdev You have Apple devices (or at least phones) that you can test this on right? I have nothing that would create the problem format in the issue.

I sure do, but I force formats, so I’d have to change and test - I’ll get that sorted!

**Comment by adiov** [comment]
Tested on macOS Safari and and iPhone Safari. On iPhone, when selecting the upload from the Camera or from the Photos gallery, the file is converted as expected. On macOS, when selecting the Photo locally or from iCloud through the Photos option, the file is converted, but when navigating to the image file in another directory, such as Downloads, the HEIC file doesn't appear. This all looks like correct and expected behavior.

**Comment by katosdev** [comment]
> Tested on macOS Safari and and iPhone Safari. On iPhone, when selecting the upload from the Camera or from the Photos gallery, the file is converted as expected. On macOS, when selecting the image locally or from iCloud through the Photos option, the file is converted, but when navigating to the image file in another directory, such as Downloads, the HEIC file doesn't appear. This all looks like correct and expected behavior.

Thanks so much for helping to test, @adiov - very much appreciated!

**Pull request merged**
