### PR TITLE
show add photo button on mobile

### LINKED ISSUE #226: Modal box content rendering issue when adding an item
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

214b16a

### What is the issue you are experiencing?

1. Depending on the size of the viewport, modal box content may be outside of the frame :
issue
(I tried on both firefox and chromium).

2. When adding a picture, it's even worse : 
issue_2
I'm using firefox (on both linux and android), but on other web browser (such a chromium), there is no issue.

I'm not familiar with the underlying technologies and documentation regarding modal boxes and tailwind is very hard to fine. I have found a patch for the first issue but don't know if it's the correct way to fix it :
```diff
diff --git a/frontend/components/Base/Modal.vue b/frontend/components/Base/Modal.vue
index fa63a92..999eb33 100644
--- a/frontend/components/Base/Modal.vue
+++ b/frontend/components/Base/Modal.vue
@@ -1,8 +1,8 @@
 <template>
   <div class="z-[999]">
     <input :id="modalId" v-model="modal" type="checkbox" class="modal-toggle" />
-    <div class="modal modal-bottom overflow-visible sm:modal-middle">
-      <div class="modal-box relative overflow-visible">
+    <div class="modal modal-bottom sm:modal-middle">
+      <div class="modal-box relative">
         <button :for="modalId" class="btn btn-circle btn-sm absolute right-2 top-2" @click="close">✕</button>
 
         <h3 class="text-lg font-bold">
```
It seems to fix the first point (add a scrollbar), but not the second issue.

### How can the maintainer reproduce the issue?

To reproduce the first issue: reduce the window size or open the developer console to reduce the viewport (using firefox or chromium).
For the second part of the issue: simply load a picture (using firefox).

### Deployment

Docker (Linux)

### Deployment Details

_No response_

### PR DESCRIPTION
**Pull request by tonyaellie**
## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

image

- Improves the add image button within the create item modal on mobile.

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes https://github.com/sysadminsmedia/homebox/discussions/213
Fixes #226 

## Summary by CodeRabbit

- **New Features**
	- Improved layout and styling of the modal's action section for a better user experience.
	- Enhanced usability of the modal with updated overflow behavior, allowing for scrollbars when content exceeds the modal's dimensions.

- **Bug Fixes**
	- Enhanced maintainability of the file selection input by utilizing Tailwind CSS classes for styling.

### CODE REVIEW

**Comment by mcarbonne** [comment]
It tested it locally and it did fix the second part of the issue #226.
By also applying the patch below, it also fix the first part of the issue.
```diff
diff --git a/frontend/components/Base/Modal.vue b/frontend/components/Base/Modal.vue
index fa63a92..999eb33 100644
--- a/frontend/components/Base/Modal.vue
+++ b/frontend/components/Base/Modal.vue
@@ -1,8 +1,8 @@
 <template>
   <div class="z-[999]">
     <input :id="modalId" v-model="modal" type="checkbox" class="modal-toggle" />
-    <div class="modal modal-bottom overflow-visible sm:modal-middle">
-      <div class="modal-box relative overflow-visible">
+    <div class="modal modal-bottom sm:modal-middle">
+      <div class="modal-box relative">
         <button :for="modalId" class="btn btn-circle btn-sm absolute right-2 top-2" @click="close">✕</button>
 
         <h3 class="text-lg font-bold">
```
But I don't know if it's the right way to fix it.

**Comment by tonyaellie** [comment]
@mcarbonne I think this should fix that, let me know if you have any issues with it.

**Comment by mcarbonne** [comment]
> @mcarbonne I think this should fix that, let me know if you have any issues with it.

Yes it does ! I tested it on both firefox and chromium.

**Review by tankerkiller125 — APPROVED** [review]

**Comment by mcarbonne** [comment]
Sadly, I think this PR introduced a new issue :
image
before:
image

It's now very difficult to select a date (because we need to scroll to reach the button, while keeping the datepicker open).

**Pull request merged**
