### PR TITLE
Implement syncing with parent item location.

### LINKED ISSUE #110: Feature Request: Ability to Move all Child Items when the Location of the Parent Item is Changed
### What is the problem you are trying to solve with this feature?

Currently, the location of a child item is not tied to the parent item. For example, if the location on a parent item is changed, the user must manually go into each child item & update the location manually to match. This can create a situation where, if the user doesn't double-check all the child items, the locations could vary and effect accurate location value roll-up.

### What is the solution you are proposing?

A toggle tooltip/switch which a user can select at the parent item level, linking the location of the parent item to all child items beneath it. To maintain flexibility with other user set-ups/use cases, I think it's advisable to keep this as an 'opt in' feature, for users who may want to keep the 'location' of parent/child items decoupled.

### What alternatives have you considered?

N/A, although I'm sure if I had a better understanding of the API, there could be a work around to this.

### Additional context

_No response_

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

### PR DESCRIPTION
**Pull request by slid1amo2n3e4**
## What type of PR is this?

- feature

## What this PR does / why we need it:

Implements ability to sync parent item's location to its children.

## Which issue(s) this PR fixes:

Fixes #110

sht do I have to also include this?: close #110 

## Summary by CodeRabbit

- **New Features**
	- Introduced a new toggle for managing item location synchronization.
	- Added functionality to synchronize child item locations with parent items.

- **Enhancements**
	- Updated item management logic to conditionally synchronize child items during updates.
	- Enhanced control over parent-child relationships in item updates.
	- Improved user notifications regarding synchronization status when editing items.

- **Tests**
	- Added test cases to verify the synchronization of child item locations with their parent.

- **Documentation**
	- Enhanced API documentation to include new properties for item synchronization.
	- Updated Swagger documentation to reflect the new synchronization capabilities.

### CODE REVIEW

**Comment by tankerkiller125** [comment]
As a note, we're basically ignore the PR Testing CI, but I needed a PR to test it on to see what's broken so I can hopefully fix it. It has no effect on if we merge this or not. Although the Go Lint does have a valid thing that @coderabbitai missed. Notably:

`Error: ST1003: should not use underscores in Go names; var child_location should be childLocation (stylecheck)`

**Comment by katosdev** [comment]
Thanks for updating to fix the underscores @slid1amo2n3e4 !
@coderabbitui full review

**Comment by katosdev** [comment]
@coderabbitai full review

**Review by katosdev — APPROVED** [review]

**Review by tankerkiller125 — APPROVED** [review]

**Comment by tankerkiller125** [comment]
> @tankerkiller125 @katosdev Anything I can do to help move this along?

This PR needs to be able to pass all the tests before we can merge it. As it stands the overall code is good, but no longer passing tests and builds for some reason.

**Comment by katosdev** [comment]
Looks like just the conflicts to me now, and then good to go? Thoughts please @tankerkiller125 ?

**Review by katosdev — APPROVED** [review]

**Comment by katosdev** [comment]
Thanks @slid1amo2n3e4 !

**Pull request merged**
